ekf_global:
  # =================================================================================================================
  # 기능: GPS와 IMU 센서 데이터 융합
  # GPS → IMU 보완: GPS의 절대 위치 정보가 IMU의 누적 오차(Drift)를 주기적으로 바로잡아 줌.
  # IMU → GPS 보완: IMU의 빠르고 연속적인 자세 데이터가 GPS의 낮은 수신율(끊김)과 순간적인 위치 오차(튐 현상) 사이를 부드럽게 채워 줌.
  # TODO : 작업 완료
  # 최종 수정일: 2025.08.18
  # 편집자 : 송준상, 이다빈
  # =================================================================================================================
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false  # 2D 모드 (Z축 고정)
    print_diagnostics: true
    debug: false

    # Frame 설정
    map_frame: map     # 지도 좌표계 (절대적인 기준)
    odom_frame: odom   # 주행 거리계(Odometry) 좌표계
    base_link_frame: base_link # 기준 좌표계
    world_frame: odom

  # ----------------------------------------------------------------
  # GPS - 위치만 사용
    odom0: /odometry/gps
    # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    odom0_config: [true,  true,  true,   # 위치 : x, y, z 사용
                   false, false, false,  # 자세 : yaw, roll, pitch 사용 안함
                   false, false, false,  # 선형속도 : vx, vy, vz, vroll 사용 안함
                   false, false, false,  # 각속도 : vroll, vpitch, vyaw 사용 안함
                   false, false, false]  # 가속도 : ax, ay, az 사용 안함
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    
  # ----------------------------------------------------------------
  # IMU - 자세, vyaw 사용
    imu0: /imure/data  # 리매핑 필요: /imure/data:=/imu/datare
  # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    imu0_config: [false, false, false,  # 위치 : x, y, z 사용 안함
                  true, true, true,     # 자세 : yaw, roll, pitch 사용 
                  false, false, false,  # 선형속도 : vx, vy, vz, vroll 사용 안함
                  false, false, true,   # 각속도 : vroll, vpitch 사용 안함, vyaw 만 사용
                  false, false, false]  # 가속도 : ax, ay, az 사용 안함
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10
    
  # ----------------------------------------------------------------
  # 프로세스 노이즈 공분산 행렬 (Process Noise Covariance)
  # 이 행렬은 '예측' 단계의 불확실성을 정의합니다.
  # 값이 클수록 '예측'을 덜 신뢰하게 되고, 센서 측정값에 더 의존하게 됩니다. 값이 작을수록 '예측'을 더 신뢰하게 됩니다.
    process_noise_covariance: [
    #  X,     Y,     Z,   Roll,  Pitch,  Yaw,   VX,    VY,    VZ,   Vroll, Vpitch, Vyaw,  AX,    AY,    AZ
      0.05,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # X
      0.0,   0.05,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # Y
      0.0,   0.0,   0.05,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # Z
      0.0,   0.0,   0.0,   0.03,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # Roll
      0.0,   0.0,   0.0,   0.0,   0.03,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # Pitch
      0.0,   0.0,   0.0,   0.0,   0.0,   0.03,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # Yaw 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.025, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # VX 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.025, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # VY 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.025, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  # VZ 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0,   0.0,   0.0,   0.0,  # VRoll
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0,   0.0,   0.0,  # VPitch
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0,   0.0,  # VYaw 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0,  # AX 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01,  0.0,  # AY 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.01  # AZ
    ]
