ekf_local:
  # =================================================================================================================
  # 역할: 단일 IMU 센서만을 사용하여 '지역(Local)' 주행 정보(Odometry)를 생성. 터널 등 GPS가 안되는 곳에서 사용
  # 시간이 지남에 따라 위치와 방향 오차가 누적됨(Drift).
  # TODO : 작업 완료
  # 최종 수정일: 2025.08.18
  # 편집자 : 송준상, 이다빈
  # =================================================================================================================
  ros__parameters:
    frequency: 100.0
    sensor_timeout: 0.1
    two_d_mode: false  # 2D 모드 (z축 고정)
    print_diagnostics: true
    debug: false

  # Frame 설정
    map_frame: map  # 지도 좌표계 (절대적인 기준)
    odom_frame: odom # 주행 거리계(Odometry) 좌표계
    base_link_frame: base_link # 기준 좌표계
    world_frame: odom
  # ----------------------------------------------------------------
  # IMU - 자세, 각속도 사용
    imu0: /imure/data 
    imu0_config: [false, false, false,   # 위치 : x, y, z 사용 안함
                   true,  true,  true,   # 자세 : yaw, roll, pitch 사용 
                   false, false, false,  # 선형속도 : vx, vy, vz, vroll 사용 안함
                   true,  true,  true,   # 각속도 : vroll, vpitch, vyaw 사용
                   false, false, false]  # 가속도 : ax, ay, az 사용 안함
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10
    imu0_nodelay: false
  # ----------------------------------------------------------------
  # 프로세스 노이즈 공분산 행렬 (Process Noise Covariance)
  # 이 행렬은 '예측' 단계의 불확실성을 정의합니다.
  # 값이 클수록 '예측'을 덜 신뢰하게 되고, 센서 측정값에 더 의존하게 됩니다. 값이 작을수록 '예측'을 더 신뢰하게 됩니다.
  # 'ekf_local' 설정에서는 GPS 같은 절대 위치 센서 없이 오직 IMU만 사용.
  # 'ekf_global' 설정에 비해 전반적인 노이즈 값이 작게 설정된 이유.
  # 외부에서 오차를 보정해 줄 정보가 없으므로, 필터 내부의 예측 모델을 강하게 신뢰해야만 
  # 안정적이고 부드러운 지역 주행 정보(local odometry)를 생성할 수 있음.
  
    process_noise_covariance: [
    #  X,     Y,     Z,   Roll,  Pitch,  Yaw,   VX,     VY,     VZ,  Vroll, Vpitch, Vyaw,   AX,    AY,    AZ  
      0.005, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # X
      0.0,   0.005, 0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # Y 
      0.0,   0.0,   0.006, 0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # Z
      0.0,   0.0,   0.0,   0.003, 0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # Roll 
      0.0,   0.0,   0.0,   0.0,   0.003, 0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # Pitch 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.006, 0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # Yaw
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0025, 0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # VX
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0025, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # VY 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.004, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   # VZ
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.001, 0.0,   0.0,   0.0,   0.0,   0.0,   # VRoll 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.001, 0.0,   0.0,   0.0,   0.0,   # VPitch
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.002, 0.0,   0.0,   0.0,   # VYaw 
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.001, 0.0,   0.0,   # AX
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.001, 0.0,   # AY
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0015 # AZ
    ]

