navsat_transform_node:
  # =================================================================================================================
  # 기능 : 지구의 GPS 좌표(위도/경도)를 로봇이 사용하는 지도 좌표(미터 단위)로 변환하여, 로봇에게 흔들리지 않는 절대적인 월드 기준점을 제공
  # 기준점 설정: 처음 수신한 GPS 위치를 지도(map)의 원점 (0,0)으로 지정합니다.
  # 방향 정렬: IMU의 방향(Yaw) 정보를 이용해 현실의 동서남북과 차량의 지도 축을 일치시킵니다.
  # 변환 발행: 위 두 정보를 종합해 map → odom 좌표 변환(TF)을 계속 발행하여, 차량의 주행 오차(Drift)를 실시간으로 보정합니다.
  # TODO : 작업 완료
  # 최종 수정일: 2025.08.18
  # 편집자 : 송준상, 이다빈
  # =================================================================================================================
  ros__parameters:
    frequency: 20.0
    delay: 3.0
    magnetic_declination_radians: -0.122  # 자기편각 (지역에 맞게 설정)
    yaw_offset: 0.0
    zero_altitude: true  # 2D 내비게이션 (고도 무시)
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false

    # Frame IDs
    map_frame_id: map    # 지도 좌표계 (절대적인 기준)
    odom_frame_id: odom  # 주행 거리계(Odometry) 좌표계
    base_link_frame_id: base_link  # 기준 좌표계
    utm_frame_id: utm

    # 데이터 품질 설정
    datum_service: datum
